### ISSUE TITLE
Could not load file or assembly Microsoft.Azure.WebJobs.Extensions.Tokens

### ISSUE THREAD

**Issue by btroppma** [Azure/azure-functions-microsoftgraph-extension#58]
Steps to reproduce:

1.  Using the azure portal
2.  Create a new function app
3.  In function App settings, set to beta
4.  In Plaftorm settings, set authentication/authorization to Authentication required, Azure AD, create new Azure AD application.
5.  Add Azure function, select the ProfilePhotoAPICSharp Template.  When prompted, install the MSGraph Extension.  Wait until installation is completed.
6.  Call the function endpoint.  Log shows the following error:

2018-06-22T17:58:06.739 [Error] Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.ProfilePhotoAPICSharp1'. System.Private.CoreLib: Could not load file or assembly 'Microsoft.Azure.WebJobs.Extensions.Tokens, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

A look at kudu shows the file Microsoft.Azure.WebJobs.Extensions.Tokens.dll is present in the /wwwroot/bin folder.

Thanks

Bob

**Comment by ConnorMcMahon** [comment]
This is currently a regression in how the functions runtime loads assemblies for extensions when using .csx files. This should be fixed in the functions runtime version 2.0.11888. Expect it in the next couple of days, as it has already been deployed to West Central US.

**Comment by qmatteoq** [comment]
Is there a way to force the runtime update? I've tried to create a new Azure Function in the West US region, but I'm still getting a version older than 2.0.11888 and, as such, I can't use the graph extension.

Thanks!
